<?php
/**
 * @Entity("tutorial") 
 */
class Tutorial extends Model
{
	/**
	 * @AutoGenerated()
	 * @Column(Type="Int",Key="Primary")
	 */
	public $Id;
	
	/**
	 * @Column(Type="Int")
	 */
	public $Date;
	
	/**
	 * @Column(Type="Int")
	 */
	public $AuthorId;
	
	/**
	 * @Column(Type="String")
	 * @Label("Título")
	 * @Required()
	 */
	public $Title;
	
	/**
	 * @Column(Type="String")
	 */
	public $Slug;
	
	/**
	 * @Column(Type="String")
	 * @Label("Conteúdo")
	 * @Required()
	 */
	public $Content;
	
	public static function all($p = 1, $m = 20, $o = 'Date', $t = 'DESC', $s = '')
	{
		$s = '%'. $s .'%';
		$db = Database::getInstance();
		return $db->ViewTutorial
				->where('Title LIKE ? OR Content LIKE ?', $s, $s)
				->orderBy($o, $t)
				->paginate(--$p, $m);
	}
}